### ISSUE TITLE
Read privilege are required for accessing "architecture and scheme memo" link 

### ISSUE THREAD

**Issue by zono1009** [kubernetes-native-testbed/kubernetes-native-testbed#783]
Hi.  :)

This is just confirmation.
I noticed that read privilege are required for accessing "architecture and scheme memo" link in README.md.
↓
https://docs.google.com/spreadsheets/d/18Pza74gohErR-58ib8nUFeJcMJaTr65Jalh7EKAVc7g/edit#gid=0

Is there any reason for this? ( be limited to contributors ? )
Or inappropriate authority setting?

**Comment by MasayaAoyama** [comment]
@zono1009 
Hi, this docs is only for contributors, because there are some personal info and credentials.
In addition, this docs is not document, this looks like memo now : |
In the future (maybe BETA-1 or BETA-2 phase), we will prepare documentation for more detailed architecture and DB schemes : )

**Comment by zono1009** [comment]
OK !! Thanks.
I close this ticket :)
