### ISSUE TITLE
automatically run `gcloud services enable container.googleapis.com`

### ISSUE THREAD

**Issue by oke-py** [kubernetes-native-testbed/kubernetes-native-testbed#787]
When I executed `tools/start.sh`, the error below occurred.
That's because I haven't enabled container.googleapis.com.
How about running `gcloud services enable container.googleapis.com` in the script?
Do you think it's better to leave it to users?

```
$ ./tools/start.sh
（snip）
ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=403, message=Kubernetes Engine API is not enabled for this project. Please ensure it is enabled in Google Cloud Console and try again: visit https://console.cloud.google.com/apis/api/container.googleapis.com/overview?project=kubernetes-native-testbed to do so.
Fetching cluster endpoint and auth data.
ERROR: (gcloud.container.clusters.get-credentials) ResponseError: code=404, message=Not found: projects/kubernetes-native-testbed/locations/asia-northeast1/clusters/testbed.
No cluster named 'testbed' in kubernetes-native-testbed.
```

**Comment by MasayaAoyama** [comment]
I think it is good.
If we can run that commands repeatedly, please add to `./tools/init.sh` .

**Comment by oke-py** [comment]
Thanks. I'll try it.

**Comment by oke-py** [comment]
If enabled, the command returns 0, and so it can be run repeatedly.
```
$ gcloud services enable container.googleapis.com

$ echo $?
0
```

**Comment by oke-py** [comment]
No errors.
![ss_ 2020-04-27 18 17 50](https://user-images.githubusercontent.com/4710215/80355843-8f203e80-88b3-11ea-98c6-a04aff0e7b01.png)

**Comment by oke-py** [comment]
@MasayaAoyama `./tools/init.sh` is good to run the command?
In my opinion, before [this line](https://github.com/kubernetes-native-testbed/kubernetes-native-testbed/blob/develop/tools/create_cluster.sh#L12) is good because it'll be run only if $KUBERNETES_PLATFORM = "gke". It's called in `./tools/start.sh`.

**Comment by MasayaAoyama** [comment]
@oke-py 
I think we need to run "service enable" at once, so `init.sh` is good location.
But if "services enable" command will be finished rapidly, it is ok to locate command in`start.sh`.

In addition, we need to consider about enable other services,
